### ISSUE TITLE
Feature Request - Link id's

### ISSUE THREAD

**Issue by 0dp** [elliottprogrammer/alphaListNav.js#11]
Hi @elliottprogrammer 

I don't know if you take requests or accepts PR's

On a project I'm working on I'm adding ID's to the `alpha-list-heading` and then adding `heading.id = _this._getHeading(key).replace(/\s/g, '');` to each heading. As such, by deactivating `e.preventDefault();` on click we get anchors.

**Comment by elliottprogrammer** [comment]
@0dp, Thanks again for the feature request! 
I've added heading id's just like you described above. Added in commit https://github.com/elliottprogrammer/alphaListNav.js/commit/fc057977b5c6d755e2bd0137a8f0ea76f62b63e4. 👍
