### ISSUE TITLE
Feature Request - htag select

### ISSUE THREAD

**Issue by 0dp** [elliottprogrammer/alphaListNav.js#12]
```
         new AlphaListNav(el, {
            ...
            headingTag: (string)
            ...
        }); 
```

ie. `headingTag: "h2"

**Comment by elliottprogrammer** [comment]
@0dp, Thanks for the feature request!  Apologies for such a delayed response.
I've added the `letterHeadingTag` option in commit https://github.com/elliottprogrammer/alphaListNav.js/commit/fc057977b5c6d755e2bd0137a8f0ea76f62b63e4. 👍
