### ISSUE TITLE
Not working on Iphones

### ISSUE THREAD

**Issue by pshort888** [elliottprogrammer/alphaListNav.js#2]
Hi Elliott,
The alphaListNav is not working on IOS 13.7  - do you know why?
Thank you.

**Comment by elliottprogrammer** [comment]
> Hi Elliott,
> The alphaListNav is not working on IOS 13.7 - do you know why?

@pshort888 , sorry for the delayed response.  Thanks for posting the issue. 👍  
I'll take look this weekend and see if I can fix for IOS. I'll let you know what I find 🙂

**Comment by 0dp** [comment]
Hi @elliottprogrammer 
Was this ever confirmed and if so fixed?

**Comment by elliottprogrammer** [comment]
There have been various updates since this issue was first reported and this issue has since been fixed.
`alphaListNav` is working good on iPhones and all other mobile devices that I am aware of. 👍
