### ISSUE TITLE
Eslint problem 

### ISSUE THREAD

**Issue by cfabrice** [elliottprogrammer/alphaListNav.js#3]
Hello and thanks for this !
Not sure but I'm using your script in a wordpress sage based theme (roots) and the linter screams no matter what I do at the line starting with
 `init = () => {` 
with 
"parsing error: Unexpected token ="
Is there a way to write this so that the linter keeps quiet ?
I've tried ignore line, file, without success... 
in the meantime I copied it directly into the page in a script tag but that's quite dirty ;-)
Thanks again anyway !

**Comment by elliottprogrammer** [comment]
Hello @cfabrice , Thanks for submitting the issue. Try using the `alphaListNav.js` file in the `/dist` folder (`dist/alphaListNav.js`). Let me know if that fixes your issue. 🙂

**Comment by cfabrice** [comment]
it worked thanks !
